# Generated by Django 5.1.1 on 2024-10-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikazioarenIzena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.BigIntegerField(default=0)),
            ],
        ),
    ]
