# Generated by Django 5.1.1 on 2024-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikazioarenIzena', '0002_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikasgaiak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('maila', models.CharField(max_length=75)),
                ('hizkuntza', models.CharField(max_length=75)),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
