# Generated by Django 5.1.1 on 2024-10-03 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikazioarenIzena', '0003_ikasgaiak_delete_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('oharra', models.CharField(max_length=75)),
                ('ikasgai_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikazioarenIzena.ikasgaiak')),
                ('ikasle_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikazioarenIzena.ikasle')),
            ],
        ),
    ]
