# Generated by Django 5.1.1 on 2024-10-07 08:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=75)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Alokatuta', 'Alokatuta'), ('Libre', 'Libre')], default='Libre', max_length=30)),
                ('potencia', models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=100)),
                ('alokatze_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
