# Generated by Django 5.1.1 on 2024-10-07 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ibilgailu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotxe',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='kotxe',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='pertsona',
            name='alokatze_data',
        ),
        migrations.AddField(
            model_name='kotxe',
            name='alokatzailea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ibilgailu.pertsona'),
        ),
        migrations.AddField(
            model_name='kotxe',
            name='alokatze_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kotxe',
            name='kolorea',
            field=models.CharField(default='Txuria', max_length=30),
        ),
        migrations.AddField(
            model_name='kotxe',
            name='matrikula',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kotxe',
            name='modeloa',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pertsona',
            name='helbidea',
            field=models.CharField(default='Eibar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pertsona',
            name='telefonoa',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='estado',
            field=models.CharField(choices=[('Alokatuta', 'Alokatuta'), ('Libre', 'Libre')], default='Libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='marka',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pertsona',
            name='izena',
            field=models.CharField(max_length=100),
        ),
    ]
