# Generated by Django 5.1.1 on 2024-10-12 16:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ibilgailu', '0002_remove_kotxe_modelo_remove_kotxe_potencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotxe',
            name='alokatzailea',
        ),
        migrations.RemoveField(
            model_name='kotxe',
            name='alokatze_data',
        ),
        migrations.RemoveField(
            model_name='kotxe',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='kotxe',
            name='kolorea',
        ),
        migrations.RemoveField(
            model_name='kotxe',
            name='matrikula',
        ),
        migrations.RemoveField(
            model_name='pertsona',
            name='helbidea',
        ),
        migrations.RemoveField(
            model_name='pertsona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pertsona',
            name='telefonoa',
        ),
        migrations.AddField(
            model_name='kotxe',
            name='kilometroak',
            field=models.IntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pertsona',
            name='dni',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pertsona',
            name='emaila',
            field=models.CharField(default='proba@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='marka',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='modeloa',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Alokairua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alokairu_data_hasi', models.DateField(null=True)),
                ('alokairu_data_bukatu', models.DateField(null=True)),
                ('kotxea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ibilgailu.kotxe')),
                ('pertsona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ibilgailu.pertsona')),
            ],
        ),
    ]
